---
title: "data_testing_part2_forward"
author: "Ngoc Duong - nqd2000"
date: "2/11/2020"
output: github_document
editor_options: 
  chunk_output_type: console
---
```{r setup, echo = FALSE}
library(tidyverse)
library(MASS)
library(matrixcalc)
library(ggplot2)
library(broom)
library(pracma)
```

Write function to simulate dataset with 3 kinds of given predictors + null predictors

```{r}
sim_beta_strong = function(n_strong, coef_strong){
  rep(coef_strong, n_strong) + runif(n_strong, min = 0, max = coef_strong)
}


sim_data = function(n_sample = 200, n_parameter = 50, prop_strong = 0.1, prop_wbc = 0.2, prop_wai = 0.2, c = 1, cor = 0.3, coef_strong = 5) {
  # Numbers of four signals
  n_strong = as.integer(n_parameter * prop_strong) # strong
  n_wbc = as.integer(n_parameter * prop_wbc) # weak but correlated
  n_wai = as.integer(n_parameter * prop_wai) # weak and independent
  n_null = n_parameter - n_strong - n_wbc - n_wai # null
  
  if (n_null < 0) {
    return("Given parameters' proportions are not valid.")
  }
  
  bound = c * sqrt(log(n_parameter) / n_sample) # threshold of weak/strong, the default is 0.14
  if (coef_strong < bound) {
    coef_strong = coef_strong + 2 * bound
  }
  
  cor_matrix = diag(n_parameter)
  
  # add correlation
  for (i in 1:n_strong) {
    cor_matrix[i, (n_strong + n_wai + i)] = cor
    cor_matrix[i, (n_strong + n_wai + n_wbc + 1 - i)] = cor
    cor_matrix[(n_strong + n_wai + i), i] = cor
    cor_matrix[(n_strong + n_wai + n_wbc + 1 - i), i] = cor
  }
  
  
  if (!is.positive.definite(cor_matrix)) {
    return("The correlation matrix is not valid.")
  }
  
  # simulate the data from multivariate normal
  X = mvrnorm(n = n_sample, mu = rep(0, n_parameter), Sigma = cor_matrix) # var = 1, correlation = covariance
  
  beta = c(
    sim_beta_strong(n_strong, coef_strong),
    runif(min = bound/2, max = bound, n = n_wai), 
    runif(min = bound/2, max = bound, n = n_wbc),
    rep(0, n_null) 
  )
  
  Y = 1 + X %*% beta + rnorm(n_sample)
  data = as_tibble(data.frame(cbind(X, Y)))
  
  # Name the columns
  cols = c(
    str_c("strong", 1:n_strong, sep = "_"),
    str_c("wai", 1:n_wai, sep = "_"),
    str_c("wbc", 1:n_wbc, sep = "_"),
    str_c("null", 1:n_null, sep = "_"),
    "Y"
   )
   colnames(data) = cols
   data = data %>% 
     dplyr::select(Y, everything())
   
  masterlist = list(beta = beta, 
       correlation = cor,
       n_parameter = n_parameter,
       prop_strong = prop_strong,
       prop_wbc = prop_wbc, 
       prop_wai = prop_wbc,
       n_strong = n_strong,
       n_wai = n_wai,
       n_wbc = n_wbc,
       data = data
       )
}
```

Function implementing forward selection method using AIC as criterion
```{r}
forward.aic.lm = function(df) {
  null.lm = lm(Y ~ 1, data = df)
  full.lm = lm(Y ~ ., data = df)
  aic.lm = step(object = null.lm,
             scope = list(lower = null.lm, 
                          upper = full.lm), 
             direction = "forward",
             trace = FALSE, 
             k = 2)
  aic.lm
}
```

```{r}
# function to remove weak predictors one by one 
mse_data = NULL
n_sim = 30
cor = c(0.3, 0.7)

for(n in n_sample){
for(c in cor){
for (i in 0:20) {
  for (j in 1:30) {
     data_list = sim_data(n_sample = 100, n_parameter = 50, cor = c)
     df = data_list$data %>% 
       dplyr::select(Y, starts_with("strong"), 
                     starts_with("wbc"), 
                     starts_with("wai"), 
                     everything())
     df_delete = df[-c(7:(7+i))]
     
 # create the forward model
    forward_lm = forward.aic.lm(df_delete)
    
    beta_est = tidy(forward_lm) %>% 
      filter(str_detect(term, "strong")) %>% 
      .[1:2] %>% 
      separate(term, 
               into = c("term", "index"), 
               sep = "_") %>% 
      mutate(index = as.numeric(index)) %>% 
      arrange(index) %>% 
      pull(estimate) 
    
    true_beta = data_list$beta[1:5]

    # Gather coefficients from estimated model that did not see some weak predictors
    
    mse_data = rbind(mse_data, 
                     tibble(mse_strong = mean((beta_est-true_beta)^2), 
                       bias_strong = mean(beta_est-true_beta), 
                       n_weak_missing = i, cor = c, n_sample = n))
  }}}}
```

```{r}
mse_data %>% 
  group_by(n_weak_missing, cor) %>% 
  summarise(mean_mse_strong = mean(mse_strong),
            mean_bias_strong = mean(bias_strong)) %>% 
  ggplot(aes(x = n_weak_missing, y = mean_mse_strong)) +
  geom_point()+geom_smooth(method = "loess", se = 2, stat = "smooth", formula = y~x) +
  facet_grid(~cor)
```


Crystal's codes adapt
```{r}
data_delete = vector("list", length = 50)
for (j in 1:50) {
data_delete[[j]] =  sim_data(n_parameter = 50, cor = 0.7)
}
```

```{r}
#get the coef of strong signals for the "true"
true_coef_forward = vector("list", length = 50)
for (j in 1:50){
  coef= data_delete[[j]][[1]]
  strong = coef[1:5]
  true_coef_forward[[j]] = strong
}
```
  
```{r}
#delete weak signals before fitting the models and construct a new list of datasets
data_new_forward = vector("list")

for (i in 1:50){
  output_forward = vector("list")
  
  for (j in 1:20){
    data = data_delete[[i]][[10]] %>% dplyr::select(Y,starts_with("strong"), starts_with("wbc"),starts_with("wai"),everything())
    output_forward[[j]] = data[-c(7:(6+j))]
  }
  data_new_forward[[i]] = output_forward
}
```

```{r}
#fit forward models using new deleted datasets
#and store the new fitted param in a new list
param_new_forward = vector("list", length = 50)
for (i in 1:50) {
  output_para_forward = vector("list", length = 20)
  for (j in 1:20) {
    data = data_new_forward[[i]][[j]]
    # forward selection
    forward_lm = forward.aic.lm(data)
    #obtain coeffcients for forward model
    a = tidy(forward_lm) %>% filter(str_detect(term, "strong")) %>% .[1:2] %>% separate(term, into = c("term", "index"), sep = "_") %>% mutate(index = as.numeric(index)) %>% arrange(index) %>% pull(estimate) %>% as.data.frame()
    rownames(a) = c(str_c("strong", 1:5, sep = "_"))
    output_para_forward[[j]] = data.frame(t(a))
  }
  param_new_forward[[i]] = output_para_forward
}
```

```{r}
# extract the fitted new strong signals' coeff in a list
fitted_coef_forward = vector('list', length = 20)
for (i in 1:50){
  output_coef_forward = vector('list', length = 20)
  for (j in 1:20){
    p = unlist(param_new_forward[[i]][j]) 
    pnames = strsplit(names(p), split = '_')
    for (n in 1:length(p)){
    names(p)[n] = pnames[[n]][1]
    }
    output_coef_forward[[j]] = p[names(p)=='strong']
  }
  fitted_coef_forward[[i]] = output_coef_forward
}
```

MSE and bias data manipulate
```{r}
#MSE data manipulate
mse_df_forward = NULL
mse_list_forward = NULL
mse_df_forward = data.frame(matrix (ncol = 0, nrow = 20))
for (i in 1:50){
  mse_list_forward = data.frame(matrix (ncol = 0, nrow = 20))
  for (j in 1:20){
    mse_col_forward = mean((true_coef_forward[[i]] - as.vector(fitted_coef_forward[[i]][[j]]))^2)
    mse_list_forward = cbind(mse_list_forward,mse_col_forward)
    names(mse_list_forward)[j] = j
  }
  mse_df_forward =cbind(mse_df_forward,mse_list_forward)
}

#bias data manipulate
bias_df_forward = NULL
bias_list_forward = NULL
bias_df_forward = data.frame(matrix(ncol = 0, nrow = 20))
for (i in 1:50){
  bias_list_forward = data.frame(matrix(ncol = 0, nrow = 20))
  for (j in 1:20){
    bias_col_forward = mean(true_coef_forward[[i]] - as.vector(fitted_coef_forward[[i]][[j]]))
    bias_list_forward = cbind(bias_list_forward,bias_col_forward)
    names(bias_list_forward)[j] = j
  }
  bias_df_forward =cbind(bias_df_forward, bias_list_forward)
}
```

Put data in right form to visualize 
```{r}
mse_df_forward_test = mse_df_forward %>% 
  pivot_longer(
    everything(),
    names_to = "n_missing",
    values_to = "mse") %>% 
  dplyr::select(mse, n_missing) %>% 
  mutate(n_missing = as.numeric(n_missing)) %>% 
  group_by(n_missing) %>% 
  summarise(mean = mean(mse)) %>% 
  mutate(measure = "mse") 

bias_df_forward_test = bias_df_forward %>% 
  pivot_longer(
    everything(),
    names_to = "n_missing",
    values_to = "bias") %>% 
  dplyr::select(bias, n_missing) %>% 
  mutate(n_missing = as.numeric(n_missing)) %>% 
  group_by(n_missing) %>% 
  summarise(mean = mean(bias)) %>% 
  mutate(measure = "bias")


forward_task2_cor7 = rbind(mse_df_forward_test, bias_df_forward_test) %>% mutate(type = "Forward", cor = 0.7)

```

```{r}
forward_task2_cor3 = forward_task2_data %>% mutate(cor = 0.3)

task2_data_cor = rbind(forward_task2_cor7, forward_task2_cor3)

task2_data_cor %>% filter(measure == "mse") %>% 
  group_by(n_missing, cor) %>% 
  summarise(mean_mse_strong = mean(mean)) %>% 
  ggplot(aes(x = n_missing, y = mean_mse_strong)) +
  geom_point()+geom_smooth(method = "loess", se = 2, stat = "smooth", formula = y~x) +
  facet_grid(~cor)

task2_data_cor %>% filter(measure == "bias") %>% 
  group_by(n_missing, cor) %>% 
  summarise(mean_bias_strong = mean(mean)) %>% 
  ggplot(aes(x = n_missing, y = mean_bias_strong)) +
  geom_point()+geom_smooth(method = "loess", se = 2, stat = "smooth", formula = y~x) +
  facet_grid(~cor)
```

Visualize!!
```{r}
final_data = rbind(forward_task2_data, lasso_task2_data)

final_data %>% filter(measure == "bias") %>% 
  ggplot(aes(x = n_missing, y = mean, group = type)) +
  geom_point(aes(color = type)) +
  geom_smooth(aes(color = type), method = "loess", se = T, formula = y~x) + theme_bw() + 
  labs(title = "Average bias of strong signals against the number of missing weak signals") +
  theme_bw() +
  scale_y_continuous("Bias of strong signals") + 
  scale_x_continuous("Number of missing weak signals") +
  scale_colour_discrete("") + 
  theme(legend.position = "bottom",
      plot.title = 
          element_text(hjust = 0.5, 
                       size=12, 
                       face='bold'))

final_data %>% filter(measure == "mse") %>% 
  ggplot(aes(x = n_missing, y = mean, group = type)) +
  geom_point(aes(color = type)) +
  geom_smooth(aes(color = type), method = "loess", se = T, formula = y~x) + theme_bw() + 
  labs(title = "Average MSE of strong signals against the number of missing weak signals") +
  theme_bw() +
  scale_y_continuous("Average MSE and bias of strong signals") + 
  scale_x_continuous("Number of missing weak signals") +
  scale_colour_discrete("") + 
  theme(legend.position = "bottom",
      plot.title = 
          element_text(hjust = 0.5, 
                       size=12, 
                       face='bold'))


forward_task2_data %>% filter(measure == "bias") %>% 
  ggplot(aes(x = n_missing, y = mean)) +
  geom_point(aes()) +
  geom_smooth(method = "loess", se = T, formula = y~x) + theme_bw() + 
  labs(title = "Average bias of strong signals against the number of missing weak signals") +
  theme_bw() +
  scale_y_continuous("Bias of strong signals") + 
  scale_x_continuous("Number of missing weak signals") +
  scale_colour_discrete("") + 
  theme(legend.position = "bottom",
      plot.title = 
          element_text(hjust = 0.5, 
                       size=12, 
                       face='bold'))
```


