---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rmarkdown")
library(ggplot2)
library(patchwork)
```

```{r}
df = rbind(df_0.3,df_0.5,df_0.7)
```

```{r}
p2 = df %>% ggplot(aes(x = n_parameter_total))+
 geom_point(aes(y=strong_prfm*100, color="prop_strong")) +
 geom_point(aes(y=wai_prfm*100, color="prop_wai")) + 
 geom_point(aes(y=wbc_prfm*100, color="prop_wbc")) + 
 geom_point(aes(y=null_prfm*100, color="prop_null")) + 
  geom_line(aes(y=strong_prfm*100, color="prop_strong")) +
  geom_line(aes(y=wai_prfm*100, color="prop_wai")) + 
  geom_line(aes(y=wbc_prfm*100, color="prop_wbc")) + 
  geom_line(aes(y=null_prfm*100, color="prop_null")) + 
 labs(title = "LASSO",
       y = "Percent of signals included in the model (%)",
       x = "Number of (pre-set) total parameters") +  
  theme_bw() + 
  theme(plot.title = 
          element_text(hjust = 0.5, 
                       size=12, 
                       face='bold'), 
          legend.position = "bottom") +
  scale_color_discrete(name = "Type", labels = c( "Null","Strong" ,"WAI", "WBC"))  +
     facet_grid(~corr)

```

```{r}
plot_lasso11 = df %>% 
  ggplot(aes()) +
  geom_density(aes(x = prop_wbc, color = "WBC")) + 
  geom_density(aes(x=prop_wai, color = "WAI")) +
  facet_grid(rows = vars(corr), cols = vars(n_parameter_total)) +
  theme(legend.title=element_blank())+
  labs(title = "Distribution of Weak Signals Identified by LASSO Model",
       x = "Percent of weak signals included in the model (%)",
       y = "Density") +  
   theme_bw()+
  theme(plot.title = 
          element_text(hjust = 0.5, 
                       size=12, 
                       face='bold'), 
          legend.position = "bottom") +
  scale_color_discrete(name = "Signal Type", labels = c( "WAI", "WBC"))
```

```{r}
p1+p2
```

